apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-example-8080
  name: hello-example-8080
spec:
  selector:
    matchLabels:
      app: hello-example-8080
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-example-8080
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-example-8080
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-example-8080
  name: lb-hello-example-8080
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-example-8080
  type: LoadBalancer
